### ISSUE TITLE
Do not require prompts, support all operations via flags too

### ISSUE THREAD

**Issue by moritzraho** [adobe/aio-cli-lib-console#14]
### Expected Behaviour

CLIs should never require to prompt, to work also with non TTY environments (e.g. CICD).

This is also true for resource creation (create Workspace, Project, add services, ..).

For operations that require many inputs, consider using --input json input files

**Comment by purplecabbage** [comment]
Flags or args ... great call out!

**Comment by purplecabbage** [comment]
Closing this as this repo is now a lib and not a cli plugin
